version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_orders
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - orders_network

  app:
    build: .
    container_name: orders_app
    restart: always
    ports:
      - "8000:8000"   # REST API
      - "50051:50051" # gRPC
      - "8080:8080"   # GraphQL
    depends_on:
      - mysql
    environment:
      DB_DRIVER: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: orders
      WEB_SERVER_PORT: 8000
      GRPC_SERVER_PORT: 50051
      GRAPHQL_SERVER_PORT: 8080
    networks:
      - orders_network

volumes:
  mysql_data:

networks:
  orders_network:
    driver: bridge

